using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Model.Migrations
{
    /// <inheritdoc />
    public partial class initData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
table: "Roles",
columns: new[] { "Id", "Name", "IsActive", "Created", "Modified", "CreatedBy", "ModifiedBy" },
values: new object[,]
{
        {
             1,
             "Admin",
             false,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             2,
             "Planning Engineer",
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             3,
             "User",
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
});
            migrationBuilder.InsertData(
            table: "Users",
            columns: new[] { "Id", "Username", "Password", "FirstName", "LastName", "Designation", "Email", "RoleID", "IsActive", "Created", "Modified", "CreatedBy", "ModifiedBy" },
            values: new object[,]
            {
        {
             1,
             "Admin",
             "Secret@123",
             "Admin",
             "",
             "Super User",
             "testtimer@mailinator.com",
             1,
             false,
             DateTime.UtcNow,
             DateTime.UtcNow,
             1,
             1
        }
            });
            migrationBuilder.InsertData(
           table: "Permissions",
           columns: new[] { "Id", "Name", "Description", "IsActive", "Created", "Modified", "CreatedBy", "ModifiedBy" },
           values: new object[,]
           {
        {
             1,
             "Audit",
             "",
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             2,
             "Project",
             "",
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             3,
             "Request",
             "",
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             4,
             "TimeLog",
             "",
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             5,
             "User",
             "",
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
           });

            migrationBuilder.InsertData(
           table: "RolePermissions",
           columns: new[] { "Id", "RoleID", "PermissionID", "View", "Insert", "Update", "Delete", "AllData", "IsActive", "Created", "Modified", "CreatedBy", "ModifiedBy" },
           values: new object[,]
           {
        {
             1,
             1,
             1,
             true,
             true,
             true,
             true,
             true,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             2,
             1,
             2,
             true,
             true,
             true,
             true,
             true,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             3,
             1,
             3,
             true,
             true,
             true,
             true,
             true,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             4,
             1,
             4,
             true,
             true,
             true,
             true,
             true,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             5,
             1,
             5,
             true,
             true,
             true,
             true,
             true,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             6,
             2,
             1,
             false,
             false,
             false,
             false,
             false,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             7,
             2,
             2,
             true,
             true,
             true,
             true,
             true,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             8,
             2,
             3,
             true,
             true,
             true,
             true,
             true,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             9,
             2,
             4,
             true,
             true,
             true,
             true,
             true,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             10,
             2,
             5,
             true,
             true,
             true,
             true,
             true,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             11,
             3,
             1,
             false,
             false,
             false,
             false,
             false,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             12,
             3,
             2,
             false,
             false,
             false,
             false,
             false,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             13,
             3,
             3,
             true,
             true,
             true,
             true,
             false,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             14,
             3,
             4,
             true,
             true,
             true,
             true,
             false,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
        {
             15,
             3,
             5,
             true,
             false,
             false,
             false,
             false,
             true,
             DateTime.UtcNow,
             DateTime.UtcNow,
             "Admin",
             "Admin"
        },
           });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
